version: '3'
services:
  db:
    image: nakaken0629/tech-for-webdev-db
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password1234
  web:
    image: nakaken0629/tech-for-webdev-web
    container_name: web
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
