version: '3'
services:
  dev:
    build:
      context: dev
    container_name: dev
    volumes:
      - ./dev/work/:/root/
    working_dir: /root/
    command: /bin/bash
    tty: true
    stdin_open: true
