version: '3'
services:
  dev:
    build:
      context: dev
    container_name: dev
    volumes:
      - ./dev/work/:/root/
    working_dir: /root/
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
  tester:
    build:
      context: tester
    depends_on:
      - grid-firefox
      - dev
    container_name: tester
    volumes:
      - ./tester/work/:/root/
    working_dir: /root/
    command: /bin/bash
    tty: true
    stdin_open: true
  grid-firefox:
    image: selenium/standalone-firefox:4.16.1-20231219
    build:
      shm_size: "2gb"
    container_name: grid-firefox
    working_dir: /root/
    ports:
      - 4444:4444
