version: '3'
services:
  dev:
    build:
      context: dev
    container_name: dev
    volumes:
      - ./dev/work/:/root/
    working_dir: /root/
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
  tester:
    build:
      context: tester
    depends_on:
      - hub
      - dev
    container_name: tester
    volumes:
      - ./tester/work/:/root/
    working_dir: /root/
    command: /bin/bash
    tty: true
    stdin_open: true
  hub:
    image: selenium/hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
  driver-chrome:
    image: selenium/node-chrome
    build:
      shm_size: "2gb"
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - START_XVFB=false
    depends_on:
      - hub
    container_name: driver-chrome
    working_dir: /root/
