version: '3'
services:
  web:
    build:
      context: web
    container_name: web
    volumes:
      - ./web/work/:/usr/local/apache2/htdocs
    working_dir: /usr/local/apache2/htdocs
    ports:
      - 8080:80
